import type { Config } from "tailwindcss";

/**
 * Two Stitch design systems live in this project:
 *  - landing page ("Founder OS" style): `brand.*` colors
 *  - secondary pages ("Studio Minimal"): Material-style surface/primary tokens,
 *    named spacing and font sizes. Its radius scale is namespaced (`ds`, `ds-lg`,
 *    `ds-xl`) so it does not override Tailwind's default `rounded-*` used by the landing.
 */
const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        brand: {
          lime: "#D9F944",
          limeDark: "#b5d318",
          black: "#0a0a0a",
          muted: "#666666",
          lightMuted: "#8e8e93",
          border: "#eaeaea",
          cardBg: "#fbfbfb",
          pillBg: "#f5f5f5",
        },
        "surface-tint": "#556500",
        "surface-container": "#eeeeee",
        "inverse-on-surface": "#f0f1f1",
        "tertiary-container": "#8affeb",
        background: "#f9f9f9",
        "on-secondary-fixed-variant": "#474646",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "on-surface-variant": "#454934",
        "on-primary-container": "#5f7100",
        "error-container": "#ffdad6",
        primary: "#556500",
        "primary-fixed-dim": "#b5d318",
        "on-primary-fixed": "#181e00",
        "inverse-surface": "#2f3131",
        "on-secondary-fixed": "#1c1b1b",
        "surface-variant": "#e2e2e2",
        "on-background": "#1a1c1c",
        error: "#ba1a1a",
        "surface-dim": "#dadada",
        "on-tertiary-fixed-variant": "#005047",
        "secondary-fixed-dim": "#c9c6c5",
        "surface-container-highest": "#e2e2e2",
        tertiary: "#006b5f",
        "on-surface": "#1a1c1c",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#59dbc7",
        "on-tertiary-fixed": "#00201c",
        "surface-container-high": "#e8e8e8",
        "on-tertiary": "#ffffff",
        secondary: "#5f5e5e",
        "tertiary-fixed": "#79f7e3",
        "on-primary-fixed-variant": "#404c00",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#00776a",
        "on-secondary": "#ffffff",
        "inverse-primary": "#b5d318",
        "secondary-fixed": "#e5e2e1",
        "on-secondary-container": "#656464",
        "outline-variant": "#c6c9ae",
        surface: "#f9f9f9",
        "primary-container": "#d9f944",
        "surface-bright": "#f9f9f9",
        "surface-container-low": "#f3f3f3",
        "secondary-container": "#e5e2e1",
        "primary-fixed": "#d1f03b",
        outline: "#767962",
      },
      borderRadius: {
        ds: "1rem",
        "ds-lg": "2rem",
        "ds-xl": "3rem",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-xl": "2.5rem",
        "gutter-mobile": "1rem",
        "space-lg": "1.5rem",
        margin: "3rem",
        "space-2xl": "4rem",
        "space-md": "1rem",
        "margin-mobile": "1.25rem",
        gutter: "1.5rem",
      },
      fontFamily: {
        sans: ["var(--font-plus-jakarta)", "sans-serif"],
        mono: ["var(--font-jetbrains-mono)", "monospace"],
        "display-hero": ["var(--font-plus-jakarta)", "sans-serif"],
        "headline-sm": ["var(--font-plus-jakarta)", "sans-serif"],
        "label-lg": ["var(--font-plus-jakarta)", "sans-serif"],
        "label-pill": ["var(--font-plus-jakarta)", "sans-serif"],
        "body-lg": ["var(--font-plus-jakarta)", "sans-serif"],
        "body-sm": ["var(--font-plus-jakarta)", "sans-serif"],
        "headline-lg": ["var(--font-plus-jakarta)", "sans-serif"],
        "display-hero-mobile": ["var(--font-plus-jakarta)", "sans-serif"],
        "label-md": ["var(--font-plus-jakarta)", "sans-serif"],
        "headline-lg-mobile": ["var(--font-plus-jakarta)", "sans-serif"],
        "headline-md": ["var(--font-plus-jakarta)", "sans-serif"],
        "body-md": ["var(--font-plus-jakarta)", "sans-serif"],
      },
      fontSize: {
        "display-hero": ["56px", { lineHeight: "64px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "label-lg": ["15px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-pill": ["13px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-hero-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "label-md": ["14px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "26px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
export default config;
